on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  ecr-success-validation:
    name: Run Terratest Success Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Terratest Unit Tests
        run: |
          cd test
          go test -v -run TestECRValidateSuccess -timeout 30m ./...
  ecr-failure-validation:
    name: Run Terratest Failure Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Terratest Unit Tests
        run: |
          cd test
          go test -v -run TestECRValidateFailure -timeout 30m ./...

